### ISSUE TITLE
Problem in zh_CN environment

### ISSUE THREAD

**Issue by ucSec** [sparkylinux/sparky-su#2]
Hi!
I tried to use 
```sh
spsu sparky-aptus-upgrade
```
however, the out put of command is all in English, but not in Chinese like 
```sh
sudo sparky-aptus-upgrade
```
***
I tried to use 
```sh
spsu sparky-aptus
```
behave like
![](https://img.vim-cn.com/6c/bfd90bcd42d3e55ad460aa95c8bc2327969900.png)
not like
```sh
sudo sparky-aptus
```
![](https://img.vim-cn.com/2b/80c820245b908c8ac2abbf2bddaccfdf5f90cc.png)
***
probably with
https://github.com/sparkylinux/sparky-su/blob/bd3d8c1e743da0377bf840c3a9dc34deb420fa8c/bin/spsu#L101
https://github.com/sparkylinux/sparky-su/blob/bd3d8c1e743da0377bf840c3a9dc34deb420fa8c/bin/spsu#L102
***
Thanks.

**Comment by pavroo** [comment]
Don't use spsu/spsudo, it is used with one app only.
The default tool of all sparky tools is remsu which calls pkexec, for example:
remsu sparky-aptus
or try:
spsudo sparky-aptus
instead.

**Comment by ucSec** [comment]
Actually.. I create this issue because the program `sparky-aptus-upgrade-checker` uses it (line 70):
````sh
if [ "$SPSU" != "" ]; then
	ROOTEXEC="spsu"
elif [ "$KTSUSS" != "" ]; then
	ROOTEXEC="ktsuss"
elif [ "$SUTOROOT" != "" ]; then
	ROOTEXEC="su-to-root -X -c"
else
	echo "no ktsuss, spsu nor su-to-root commands found... exiting.."
	exit 1
fi
````

**Comment by pavroo** [comment]
Sent update out so have a try now.

**Comment by ucSec** [comment]
solved
